import { ISSUE_TYPES, ROOMS, buildCart } from "./catalog.js";
const $ = (s, el = document) => el.querySelector(s);
const $$ = (s, el = document) => [...el.querySelectorAll(s)];
const state = { unit: "412 Maple — Unit B", rent: 1450, vacantDays: 4, cap: 900, rooms: ["Living", "Kitchen", "Bath", "Primary bed"], photos: [], issues: [], notes: "" };
const storeKey = "turnlight.v3";
function save(){try{localStorage.setItem(storeKey,JSON.stringify({unit:state.unit,rent:state.rent,vacantDays:state.vacantDays,cap:state.cap,rooms:state.rooms,issues:state.issues,notes:state.notes}))}catch{}}
function restore(){try{const raw=localStorage.getItem(storeKey);if(!raw)return;Object.assign(state,JSON.parse(raw))}catch{}}
function money(n){return n.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0})}
function dayCost(){return state.rent/30}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function samplePhotos(){const mk=(label,fill)=>{const svg=`<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400'><rect width='400' height='400' fill='${fill}'/><text x='200' y='206' text-anchor='middle' font-family='Georgia' font-size='22' fill='#f1ece3'>${label}</text></svg>`;return {name:label,src:`data:image/svg+xml;utf8,${encodeURIComponent(svg)}`}};return [mk("Living","#3d4a3f"),mk("Kitchen","#4a3c32"),mk("Bath","#2f3a44")]}
function loadSample(){state.unit="412 Maple — Unit B";state.rent=1450;state.vacantDays=6;state.cap=900;state.rooms=["Living","Kitchen","Bath","Primary bed","Hall / entry"];state.photos=samplePhotos();state.issues=[{id:1,room:"Living",type:"paint",note:"Scuffs by front door"},{id:2,room:"Living",type:"blind",note:"Broken slats"},{id:3,room:"Bath",type:"bath",note:"Missing curtain"},{id:4,room:"Kitchen",type:"kitchen",note:"Drippy faucet"},{id:5,room:"Hall / entry",type:"safety",note:"Dead smoke detector"}];state.notes="Listing Friday. Cap $900 unless we slip past day 10.";render();toast("Sample turn loaded")}
function addIssue(){state.issues.push({id:Date.now(),room:$("#issue-room").value,type:$("#issue-type").value,note:$("#issue-note").value.trim()});$("#issue-note").value="";render()}
function onFiles(files){[...files].forEach(file=>{const reader=new FileReader();reader.onload=()=>{state.photos.push({name:file.name,src:reader.result});render()};reader.readAsDataURL(file)})}
function floorSketch(){const rooms=state.rooms.length?state.rooms:["Unit"];const cols=Math.min(3,rooms.length);const w=320,h=160;const cw=(w-16)/cols;const rows=Math.ceil(rooms.length/cols);const rh=(h-16)/rows;return `<svg viewBox='0 0 ${w} ${h}' xmlns='http://www.w3.org/2000/svg'>${rooms.map((name,i)=>{const c=i%cols,r=Math.floor(i/cols),x=8+c*cw,y=8+r*rh;return `<rect x='${x}' y='${y}' width='${cw-6}' height='${rh-6}' fill='none' stroke='#1a1814'/><text x='${x+8}' y='${y+18}' font-size='10' fill='#6e6a62'>${name}</text>`}).join("")}</svg>`}
function render(){save();const cart=buildCart(state.issues,state.cap);const pay=cart.total/dayCost();$("#unit").value=state.unit;$("#rent").value=state.rent;$("#days").value=state.vacantDays;$("#notes").value=state.notes;$("#day-cost").textContent=money(dayCost());$("#vacant-cost").textContent=money(dayCost()*state.vacantDays);$("#payback").textContent=`${pay.toFixed(1)} days`;$("#cart-total-hero").textContent=money(cart.total);$("#issue-count").textContent=String(state.issues.length);$("#room-count").textContent=String(state.rooms.length);document.title=`Turnlight — ${state.unit}`;$$(".cap").forEach(el=>el.classList.toggle("on",Number(el.dataset.cap)===state.cap));$("#rooms").innerHTML=ROOMS.map(r=>`<button class="chip ${state.rooms.includes(r)?"on":""}" data-room="${r}">${r}</button>`).join("");$("#photos").innerHTML=state.photos.map((p,i)=>`<div class="photo"><img src="${p.src}" alt=""><button class="x" data-photo="${i}">×</button></div>`).join("")+`<label class="add-photo">Add photo<input type="file" accept="image/*" multiple capture="environment" id="file-in"></label>`;$("#issue-room").innerHTML=(state.rooms.length?state.rooms:ROOMS).map(r=>`<option>${r}</option>`).join("");$("#issue-type").innerHTML=ISSUE_TYPES.map(t=>`<option value="${t.id}">${t.label}</option>`).join("");$("#issues").innerHTML=state.issues.length?state.issues.map(i=>{const label=ISSUE_TYPES.find(t=>t.id===i.type)?.label||i.type;return `<div class="issue"><div><b>${label}</b> · ${i.room}<div class="who">${i.note||"No note"}</div></div><button data-del="${i.id}">Remove</button></div>`}).join(""):`<p class="legal">No issues yet.</p>`;$("#cart").innerHTML=cart.items.map(s=>`<div class="cart-item"><div>${s.name}${s.qty>1?` ×${s.qty}`:""}<span class="badge ${s.affiliate?"aff":"no"}">${s.affiliate?"May earn":"No affiliate"}</span><div class="merchant">${s.merchant}</div></div><div>${money(s.price*s.qty)}</div></div>`).join("")||`<p class="legal">Cart fills from issues and cap.</p>`;$("#cart-total").textContent=money(cart.total);$("#cap-label").textContent=money(state.cap);$("#under").textContent=cart.total<=state.cap?`Under cap by ${money(state.cap-cart.total)}`:"Over cap";$("#sketch").innerHTML=floorSketch();const hero=state.photos[0];$("#stage").innerHTML=hero?`<img src="${hero.src}" alt=""><div class="mark">Virtually staged — not current condition</div>`:`<div class="empty">Add a photo to preview the listing still.</div>`;$("#file-in")?.addEventListener("change",e=>onFiles(e.target.files))}
function bind(){$("#unit").addEventListener("input",e=>{state.unit=e.target.value;save()});$("#rent").addEventListener("input",e=>{state.rent=Number(e.target.value)||0;render()});$("#days").addEventListener("input",e=>{state.vacantDays=Number(e.target.value)||0;render()});$("#notes").addEventListener("input",e=>{state.notes=e.target.value;save()});$("#caps").addEventListener("click",e=>{const btn=e.target.closest(".cap");if(!btn)return;state.cap=Number(btn.dataset.cap);render()});$("#rooms").addEventListener("click",e=>{const btn=e.target.closest("[data-room]");if(!btn)return;const r=btn.dataset.room;state.rooms=state.rooms.includes(r)?state.rooms.filter(x=>x!==r):[...state.rooms,r];render()});$("#photos").addEventListener("click",e=>{const x=e.target.closest("[data-photo]");if(!x)return;state.photos.splice(Number(x.dataset.photo),1);render()});$("#issues").addEventListener("click",e=>{const b=e.target.closest("[data-del]");if(!b)return;state.issues=state.issues.filter(i=>i.id!==Number(b.dataset.del));render()});$("#add-issue").addEventListener("click",addIssue);$("#sample").addEventListener("click",loadSample);$("#print").addEventListener("click",()=>window.print());$("#reset").addEventListener("click",()=>{Object.assign(state,{photos:[],issues:[],notes:"",rooms:["Living","Kitchen","Bath"],cap:900,vacantDays:0});render();toast("Turn cleared")})}
document.addEventListener("DOMContentLoaded",()=>{restore();bind();render()});
